### ISSUE TITLE
Anyone manage to get this to work with Nuxt 3?

### ISSUE THREAD

**Issue by peacheszm** [nuxt-community/onesignal-module#41]
I just get this error
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'mode')                                           11:32:32 AM
  at nuxtOneSignal (./node_modules/@nuxtjs/onesignal/index.js:16:20)

**Comment by PurinWang** [comment]
Me too, Use Nuxt 3 and get this message, No idea how to fix, maybe use include origin js file

**Comment by harlan-zw** [comment]
Doesn't seem like it, have made an issue to track here: https://github.com/nuxt-community/onesignal-module/issues/41
